### ISSUE TITLE
Errors running call_main.py

### ISSUE THREAD

**Issue by adchdev** [hidayatkhan013/Dark-web-Crawler#2]
Running app.py works but running call_main.py in Python 3.8 returns:

```
Traceback (most recent call last):
  File "call_main.py", line 34, in <module>
    if not isTorRunning('tor.exe'):
  File "/home/acwh0110/Dark-web-Crawler/Crawler/launch_tor.py", line 14, in isTorRunning
    output = subprocess.check_output(call).decode()
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'TASKLIST'
```

When running in Python 3.10:

```
Traceback (most recent call last):
  File "/home/acwh0110/Dark-web-Crawler/Crawler/call_main.py", line 6, in <module>
    from P_queue import *
  File "/home/acwh0110/Dark-web-Crawler/Crawler/P_queue.py", line 4, in <module>
    import tldextract
ModuleNotFoundError: No module named 'tldextract'
```

Even though I've already installed tldextract using pip.

**Comment by hidayatkhan013** [comment]
check you have tor.exe
check path of tor in call_main.py
